export enum ETierRemark {
  FIRST_TRANSACTION = 'FIRST TRANSACTION',
  UPGRADE = 'UPGRADE TO NEXT TIER',
  DOWNGRADE = 'DOWNGRADE TO PREVIOUS TIER',
  RESET = 'RESET TO FIRST TIER',
  MAXIMUM = 'ALREADY GET POINT MAX TIER LEVEL',
  NONE = '',
}
